"use client"

import { KeyboardEvent, Suspense, useEffect, useState } from 'react'
import { useSearchParams } from 'next/navigation'
import { Lightbulb, Plus, ThumbsUp, X } from 'lucide-react'
import DashboardShell from '../_components/shell'

type Idea = { id:string; title:string; description?:string|null; category?:string|null; status:string }
type GroupRow = { group_id:string; groups:{name:string}|null }
const categories = ['Trip','Food','Hangout','Activity','Random']

function IdeasContent() {
  const searchParams = useSearchParams()
  const [ideas,setIdeas]=useState<Idea[]>([]),[groups,setGroups]=useState<GroupRow[]>([])
  const [open,setOpen]=useState(searchParams.get('new')==='1'),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const [title,setTitle]=useState(''),[description,setDescription]=useState(''),[category,setCategory]=useState('')
  const [showDetails,setShowDetails]=useState(false),[voted,setVoted]=useState<Record<string,boolean>>({})

  async function load(){const [g,i]=await Promise.all([fetch('/api/groups'),fetch('/api/ideas')]);const gd=await g.json().catch(()=>({}));const id=await i.json().catch(()=>({}));if(g.ok)setGroups(gd.groups||[]);if(i.ok)setIdeas(id.ideas||[])}
  useEffect(()=>{const timer=window.setTimeout(()=>{load().catch(()=>{})},0);return()=>window.clearTimeout(timer)},[])

  function reset(){setTitle('');setDescription('');setCategory('');setShowDetails(false);setOpen(false);setError('')}
  async function addIdea(){if(!title.trim()||busy)return;setBusy(true);setError('');const groupId=groups[0]?.group_id;if(!groupId){setError('Create a Link first.');setBusy(false);return}const r=await fetch('/api/ideas',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({group_id:groupId,title:title.trim(),description:description.trim()||null,category:category||null})});const d=await r.json().catch(()=>({}));if(!r.ok)setError(d.error||'Could not add idea');else{setIdeas([d.idea,...ideas]);reset()}setBusy(false)}
  function key(e:KeyboardEvent<HTMLInputElement>){if(e.key==='Enter')addIdea()}
  async function vote(id:string){const r=await fetch('/api/ideas/vote',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ideaId:id})});if(!r.ok){const d=await r.json().catch(()=>({}));setError(d.error||'Vote failed');return}setVoted(v=>({...v,[id]:!v[id]}));load().catch(()=>{})}

  return <DashboardShell title="Ideas" eyebrow="BRAIN DUMP">
    <div className="mb-6"><p className="text-sm font-medium text-zinc-500">Throw something into the mix. Let the Link decide.</p>{groups[0]?.groups?.name&&<p className="mt-1 text-[10px] font-black uppercase tracking-[.14em] text-zinc-400">{groups[0].groups.name}</p>}</div>
    {!open?<button onClick={()=>setOpen(true)} className="group mb-7 flex w-full items-center gap-4 rounded-2xl border-2 border-[#1a1a1a] bg-white p-5 text-left shadow-[4px_4px_0_#1a1a1a] transition hover:-translate-y-0.5 hover:shadow-[6px_6px_0_#1a1a1a]"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-xl border-2 border-[#1a1a1a] bg-brand-lemon"><Plus size={22}/></span><span><span className="block text-lg font-black">Got an idea?</span><span className="block text-xs font-medium text-zinc-500">Tap here and get it on the board.</span></span></button>:
    <div className="mb-7 brutal-card overflow-hidden p-5"><div className="mb-4 flex items-center justify-between"><div><div className="text-[10px] font-black uppercase tracking-[.14em] text-zinc-400">New idea</div><h2 className="text-2xl font-black">What should we do?</h2></div><button onClick={reset} className="rounded-lg p-2 hover:bg-zinc-100"><X size={18}/></button></div><input autoFocus onKeyDown={key} value={title} onChange={e=>setTitle(e.target.value)} className="brutal-input w-full rounded-xl px-4 py-4 text-base font-bold" placeholder="e.g. Sunrise hike at Mission Peak"/><div className="mt-4 flex flex-wrap gap-2">{categories.map(c=><button key={c} type="button" onClick={()=>setCategory(category===c?'':c)} className={`rounded-full border-2 border-[#1a1a1a] px-3 py-2 text-xs font-black transition ${category===c?'bg-brand-lemon shadow-[2px_2px_0_#1a1a1a]':'bg-white hover:bg-zinc-100'}`}>{c}</button>)}</div><button onClick={()=>setShowDetails(v=>!v)} className="mt-4 text-xs font-black underline decoration-2 underline-offset-2">{showDetails?'Hide details':'Add details (optional)'}</button>{showDetails&&<textarea value={description} onChange={e=>setDescription(e.target.value)} className="brutal-input mt-3 w-full rounded-xl px-4 py-3 text-sm" rows={3} placeholder="Anything the crew should know?"/>}<div className="mt-5 rounded-xl border-2 border-dashed border-zinc-300 bg-zinc-50 p-4"><div className="text-[9px] font-black uppercase tracking-[.14em] text-zinc-400">Preview</div><div className="mt-2 text-lg font-black">{title||'Your idea goes here'}</div>{category&&<div className="mt-1 text-[10px] font-black uppercase tracking-wider text-zinc-400">{category}</div>}{description&&<p className="mt-2 text-xs text-zinc-500">{description}</p>}</div>{error&&<div className="mt-3 rounded-lg border-2 border-[#1a1a1a] bg-brand-coral px-3 py-2 text-xs font-bold">{error}</div>}<button disabled={!title.trim()||busy} onClick={addIdea} className="brutal-btn mt-4 w-full justify-center rounded-xl bg-brand-mint px-4 py-3 text-sm disabled:cursor-not-allowed disabled:opacity-40">{busy?'Posting…':'Put it on the board'}<Plus size={15}/></button><p className="mt-2 text-center text-[10px] font-bold text-zinc-400">Press Enter to post</p></div>}
    {ideas.length===0?<div className="brutal-card p-10 text-center"><Lightbulb className="mx-auto" size={28}/><h2 className="mt-4 text-2xl font-black">Your board is empty.</h2><p className="mt-2 text-sm text-zinc-500">Be the first person to throw something into the mix.</p></div>:<div className="space-y-3">{ideas.map((idea,i)=><div key={idea.id} className="brutal-card flex items-center gap-4 p-5 transition hover:-translate-y-0.5"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-xl border-2 border-[#1a1a1a] bg-brand-lemon shadow-[3px_3px_0_#1a1a1a]"><Lightbulb size={20}/></div><div className="min-w-0 flex-1"><div className="text-[10px] font-black text-zinc-400">{String(i+1).padStart(2,'0')} · {idea.category||'Idea'}</div><div className="mt-1 text-base font-black">{idea.title}</div><div className="mt-1 text-xs font-medium text-zinc-500">{idea.description||'No extra details.'}</div></div><button onClick={()=>vote(idea.id)} className={`flex shrink-0 items-center gap-2 rounded-lg border-2 border-[#1a1a1a] px-3 py-2 text-xs font-black transition ${voted[idea.id]?'bg-brand-mint shadow-[2px_2px_0_#1a1a1a]':'bg-white hover:bg-brand-lemon'}`}><ThumbsUp size={14}/>{voted[idea.id]?'Voted':'Vote'}</button></div>)}</div>}
  </DashboardShell>
}
export default function IdeasPage(){return <Suspense fallback={<DashboardShell title="Ideas" eyebrow="BRAIN DUMP"><div className="brutal-card p-10 text-sm text-zinc-500">Loading ideas…</div></DashboardShell>}><IdeasContent/></Suspense>}
