"use client"
import GroupsBoard from './groups-board'

import { FormEvent, useEffect, useState } from 'react'
import { Check, Copy, Link2, Plus, Share2 } from 'lucide-react'
import DashboardShell from '../_components/shell'

type GroupRow={group_id:string;role:string;groups:{id:string;name:string;description?:string|null}|null}

export default function GroupsPage(){return <DashboardShell title="Your links" eyebrow="THE PEOPLE YOU PLAN WITH"><GroupsBoard/></DashboardShell>}

function LegacyGroupsPage(){
 const [links,setLinks]=useState<GroupRow[]>([]);const [name,setName]=useState('');const [description,setDescription]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [inviteFor,setInviteFor]=useState('');const [inviteUrl,setInviteUrl]=useState('');const [copied,setCopied]=useState(false)
 async function load(){const r=await fetch('/api/groups');const d=await r.json().catch(()=>({}));if(r.ok)setLinks(d.groups||[])}
 useEffect(()=>{load().catch(()=>{})},[])
 async function create(e:FormEvent){e.preventDefault();setBusy(true);setError('');const r=await fetch('/api/groups',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,description})});const d=await r.json().catch(()=>({}));if(!r.ok)setError(d.error||'Could not create link');else{setLinks([{group_id:d.group.id,role:'owner',groups:d.group},...links]);setName('');setDescription('')}setBusy(false)}
 async function createInvite(groupId:string){setInviteFor(groupId);setCopied(false);setError('');const r=await fetch('/api/invites',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({groupId})});const d=await r.json().catch(()=>({}));if(!r.ok){setError(d.error||'Could not create invite');setInviteFor('');return}const url=`${window.location.origin}/join/${d.invite.code}`;setInviteUrl(url);try{await navigator.clipboard.writeText(url);setCopied(true)}catch{setCopied(false)}}
 return <DashboardShell title="Your links" eyebrow="BRING YOUR PEOPLE TOGETHER"><div className="grid gap-6 lg:grid-cols-[1.05fr_.95fr]"><div className="link-feature-card p-6 sm:p-8"><div className="link-mark-pulse"><Link2 size={24}/></div><h2 className="mt-5 text-3xl font-black tracking-tight">Make a link.</h2><p className="mt-2 max-w-md text-sm leading-6 text-zinc-500">A shared space for the people you actually want around. Plans, money, ideas, and memories all stay connected.</p><form onSubmit={create} className="mt-6 space-y-3"><input className="brutal-input w-full rounded-lg px-3 py-3 text-sm" placeholder="Name your link" required value={name} onChange={e=>setName(e.target.value)}/><textarea className="brutal-input w-full rounded-lg px-3 py-3 text-sm" rows={3} placeholder="What brings everyone together?" value={description} onChange={e=>setDescription(e.target.value)}/>{error&&<div className="rounded-lg border border-[#1a1a1a] bg-brand-coral px-3 py-2 text-xs font-bold">{error}</div>}<button disabled={busy} className="brutal-btn w-full justify-center rounded-lg bg-brand-blue px-4 py-3 text-sm">{busy?'Connecting…':'Create link'}<Plus size={16}/></button></form></div><div className="space-y-3">{links.length===0?<div className="brutal-card-soft bg-brand-lemon p-6"><div className="text-[10px] font-black tracking-[.16em]">NO LINKS YET</div><h3 className="mt-2 text-xl font-black">Start with your people.</h3><p className="mt-2 text-sm text-zinc-600">Make a link for friends, trips, school, or whatever you keep planning together.</p></div>:links.map((g,i)=><div key={g.group_id} className={`brutal-card-soft p-5 ${i%3===0?'tint-blue':i%3===1?'tint-mint':'tint-peach'}`}><div className="flex items-center gap-3"><div className="link-node"><Link2 size={16}/></div><div><div className="text-[10px] font-black uppercase tracking-[.14em] text-zinc-400">{g.role}</div><h3 className="text-xl font-black">{g.groups?.name}</h3></div></div><p className="mt-2 text-sm text-zinc-500">{g.groups?.description||'A place for your people to stay connected.'}</p><button onClick={()=>createInvite(g.group_id)} disabled={inviteFor===g.group_id} className="mt-4 inline-flex items-center gap-2 rounded-lg border-2 border-[#1a1a1a] bg-white px-3 py-2 text-xs font-black shadow-[2px_2px_0_#1a1a1a] transition hover:-translate-y-0.5 disabled:opacity-60"><Share2 size={14}/>{inviteFor===g.group_id?'Creating…':'Invite people'}</button>{inviteFor===g.group_id&&inviteUrl&&<div className="mt-3 rounded-lg border-2 border-[#1a1a1a] bg-brand-cream p-3"><div className="break-all text-[10px] font-medium text-zinc-600">{inviteUrl}</div><button onClick={async()=>{try{await navigator.clipboard.writeText(inviteUrl);setCopied(true)}catch{}}} className="mt-2 inline-flex items-center gap-2 text-xs font-black">{copied?<Check size={13}/>:<Copy size={13}/>} {copied?'Copied':'Copy invite'}</button></div>}</div>)}</div></div></DashboardShell>
}
