"use client"

import { FormEvent, useEffect, useState } from 'react'
import { Link2, Plus } from 'lucide-react'
import DashboardShell from '../_components/shell'

type GroupRow={group_id:string;role:string;groups:{id:string;name:string;description?:string|null}|null}

export default function GroupsPage(){
 const [links,setLinks]=useState<GroupRow[]>([]);const [name,setName]=useState('');const [description,setDescription]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('')
 async function load(){const r=await fetch('/api/groups');const d=await r.json().catch(()=>({}));if(r.ok)setLinks(d.groups||[])}
 useEffect(()=>{load().catch(()=>{})},[])
 async function create(e:FormEvent){e.preventDefault();setBusy(true);setError('');const r=await fetch('/api/groups',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,description})});const d=await r.json().catch(()=>({}));if(!r.ok)setError(d.error||'Could not create link');else{setLinks([{group_id:d.group.id,role:'owner',groups:d.group},...links]);setName('');setDescription('')}setBusy(false)}
 return <DashboardShell title="Your links" eyebrow="BRING YOUR PEOPLE TOGETHER"><div className="grid gap-6 lg:grid-cols-[1.05fr_.95fr]"><div className="link-feature-card p-6 sm:p-8"><div className="link-mark-pulse"><Link2 size={24}/></div><h2 className="mt-5 text-3xl font-black tracking-tight">Make a link.</h2><p className="mt-2 max-w-md text-sm leading-6 text-zinc-500">A shared space for the people you actually want around. Plans, money, ideas, and memories all stay connected.</p><form onSubmit={create} className="mt-6 space-y-3"><input className="brutal-input w-full rounded-lg px-3 py-3 text-sm" placeholder="Name your link" required value={name} onChange={e=>setName(e.target.value)}/><textarea className="brutal-input w-full rounded-lg px-3 py-3 text-sm" rows={3} placeholder="What brings everyone together?" value={description} onChange={e=>setDescription(e.target.value)}/>{error&&<div className="rounded-lg border border-[#1a1a1a] bg-brand-coral px-3 py-2 text-xs font-bold">{error}</div>}<button disabled={busy} className="brutal-btn w-full justify-center rounded-lg bg-brand-blue px-4 py-3 text-sm">{busy?'Connecting…':'Create link'}<Plus size={16}/></button></form></div><div className="space-y-3">{links.length===0?<div className="brutal-card-soft bg-brand-lemon p-6"><div className="text-[10px] font-black tracking-[.16em]">NO LINKS YET</div><h3 className="mt-2 text-xl font-black">Start with your people.</h3><p className="mt-2 text-sm text-zinc-600">Make a link for friends, trips, school, or whatever you keep planning together.</p></div>:links.map((g,i)=><div key={g.group_id} className={`brutal-card-soft p-5 ${i%3===0?'tint-blue':i%3===1?'tint-mint':'tint-peach'}`}><div className="flex items-center gap-3"><div className="link-node"><Link2 size={16}/></div><div><div className="text-[10px] font-black uppercase tracking-[.14em] text-zinc-400">{g.role}</div><h3 className="text-xl font-black">{g.groups?.name}</h3></div></div><p className="mt-2 text-sm text-zinc-500">{g.groups?.description||'A place for your people to stay connected.'}</p></div>)}</div></div></DashboardShell>
}
